import { Inter } from "@next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main >
              <button onClick={()=>document.documentElement.classList.add('dark') }>change theme</button>
                <div className="font-bold text-4xl text-green-600 dark:text-red-600"> hello </div>
            </main>
        </>
    );
}
